### ISSUE TITLE
MKLDNN build failed on ubuntu_16.04 gcc_5.4 (fixed in v4.0.0a1_i3.0.1a)

### ISSUE THREAD

**Issue by mingxiaoh** [intel/chainer#2]
Build MKLDNN failed on ubuntu_16.04 gcc_5.4  with mkldnn_version = 'ba482eca9459e3b9a8256ab07f9afa41dba34b9e' . One workaround is to downgrade gcc version to gcc4.*.

**Comment by koreyou** [comment]
It seems that it was fixed in https://github.com/01org/mkl-dnn/issues/157 .
So upgrading MKL-DNN to newer version (i.e. v0.12 ) fixed the problem for me.

**Comment by mingxiaoh** [comment]
problem fixed in v4.0.0a1_i3.0.1a
