### ISSUE TITLE
TypeError using `embed_id`

### ISSUE THREAD

**Issue by koreyou** [intel/chainer#4]
It seems that `embed_id` does not work properly because dnn.mdarray is not iterable.

```
> /home/koreyou/.pyenv/versions/intel-chainer/lib/python3.5/site-packages/chainer/functions/connection/embed_id.py(76)forward()
-> gy.reshape(x.size, -1)):
(Pdb) l
 71  
 72             if xp is numpy:
 73                 # It is equivalent to `numpy.add.at(gW, x, gy)` but ufunc.at is
 74                 # too slow.
 75                 for ix, igy in six.moves.zip(x.ravel(),
 76  ->                                          gy.reshape(x.size, -1)):
 77                     if ix == self.ignore_label:
 78                         continue
 79                     gW[ix] += igy
 80             else:
 81                 if self.ignore_label is None:
(Pdb) p gy.reshape(x.size, -1)
<Swig Object of type 'std::vector< mdarray >::value_type *' at 0x7f0e6c6f98b8>
(Pdb) p iter(gy.reshape(x.size, -1))                                    
*** TypeError: 'dnn.mdarray' object is not iterable
```

You can reproduce it by running `examples/ptb/train_ptb.py` .

I have tested it out on commit 537484c0113c790fd09affbcd97fa20e9bf6da77 with Python 3.5.3, gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) and MKL-DNN v0.12 (I have modified `mkldnn_version` to avoid https://github.com/01org/mkl-dnn/issues/157 ).

**Comment by mingxiaoh** [comment]
Ideepy mdarray does not support iteration currently. We have got a workaround patch to fix the issue, which will be included in next Intel Chainer release.

The patch is simple. You can insert codes before "for loop" in /chainer/functions/connection/embed_id.py

@@ -70,6 +70,13 @@ class EmbedIDGrad(function_node.FunctionNode):
         gW = xp.zeros(self.w_shape, dtype=gy.dtype)

         if xp is numpy:
             # FIXME:
             # currently, mdarray doesn't support "iterable"
             # transfer it back to ndarray
             # will remove this after support
             if not isinstance(gy, numpy.ndarray):
                 gy = numpy.array(gy)

             # It is equivalent to `numpy.add.at(gW, x, gy)` but ufunc.at is
             # too slow.
             for ix, igy in six.moves.zip(x.ravel(),

**Comment by koreyou** [comment]
Thanks for the clarification. I myself did a small fix like the following and it worked out all right.

```diff
--- a/chainer/functions/connection/embed_id.py                           
+++ b/home/koreyou/.pyenv/versions/intel-chainer/lib/python3.5/site-packages/chainer/functions/connection/embed_id.py                             
@@ -72,8 +72,11 @@ class EmbedIDGrad(function_node.FunctionNode):        
         if xp is numpy:                                                 
             # It is equivalent to `numpy.add.at(gW, x, gy)` but ufunc.at is                                                                      
             # too slow.                                                 
-            for ix, igy in six.moves.zip(x.ravel(),                     
-                                         gy.reshape(x.size, -1)):       
+            x_ravel = x.ravel()                                         
+            gy_reshape = gy.reshape(x.size, -1)                         
+            for i in six.moves.xrange(len(x_ravel)):                    
+                ix = x_ravel[i]                                         
+                igy = gy_reshape[i]                                     
                 if ix == self.ignore_label:                             
                     continue                                            
                 gW[ix] += igy                                           
```
